version: "3"
services:
  website:
    image: nginx 
    ports:
    - "8085:80"
    restart: always
  website2:
    image: nginx 
    ports:
    - "8086:80"
    restart: always
    networks: 
      mynetwork:
        ipv4_address: 192.168.92.21
networks:
  mynetwork:
    ipam:
      driver: default
      config: 
       - subnet: "192.168.92.0/24"

